# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# There are two btc related configs
# 1. [btc-config] is config for btc full node which should have transaction indexing
# enabled. This node should be synced and can be open to the public.
# 2. [btc-signer-config] is config for bitcoind daemon which should have only
# wallet functionality, it should run in separate network. This bitcoind instance
# will be used to sign psbt's
[btc-config]
# Btc node host
host = "localhost:18556"
# Btc node user
user = "user"
# Btc node password
pass = "pass"
# Btc network (testnet3|mainnet|regtest|simnet|signet)
network = "regtest"

[btc-signer-config]
# Btc node host
host = "localhost:18556"
# TODO: consider reading user/pass from command line
# Btc node user
user = "user"
# Btc node password
pass = "pass"
# Btc network (testnet3|mainnet|regtest|simnet|signet)
network = "regtest"

[params-config]
# The list of covenant public keys
covenant_public_keys = []

# The quorum of the covenants required to sign the transaction
covenant_quorum = 0

# The magic bytes of the network
magic_bytes = "01020304"

# The number of confirmations required for the staking transaction to be mature
w = 100

# Timelock in unbonding transaction
unbonding_time = 100

# Required fee for unbonding transaction
unbonding_fee = 10000

[server-config]
# The address to listen on
host = "127.0.0.1"

# The port to listen on
port = 9791

# Read timeout in seconds
read-timeout = 15

# Write timeout in seconds
write-timeout = 15

# Idle timeout in seconds
idle-timeout = 120

