# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

# There are two btc related configs
# 1. [btc-config] is config for btc full node which should have transaction indexing
# enabled. This node should be synced and can be open to the public.
# 2. [btc-signer-config] is config for bitcoind daemon which should have only
# wallet functionality, it should run in separate network. This bitcoind instance
# will be used to sign psbt's
[btc-config]
# Btc node host
host = "bitcoind.bitcoind-signet:38332"
# Btc node user
user = "XX"
# Btc node password
pass = "XX"
# Btc network (testnet3|mainnet|regtest|simnet|signet)
network = "signet"

[btc-signer-config]
# Btc node host
host = "bitcoind.bitcoind-signet:38332"
# Btc node user
user = "XX"
# Btc node password
pass = "XX"
# Btc network (testnet3|mainnet|regtest|simnet|signet)
network = "signet"

[params-config]
# The list of covenant public keys
covenant_public_keys = ["0238229981b0de122a6528a05df266bcdf0c8e499bbe3a705032c6badec3587336", "029e471d813e82e4685a1d814902809d207e6f71d5dcb41f55450e9111659ca6a7", "0238da2198ab73f569c5885dd5c13388eaaf38bc7407330bddf10645039c64ca3c", "03c77d4a7f2406b6d66b606d2cad7c8fc900f5243beca762afea66cdbb014892b2", "03e2b49e1b0c6f79e124a469465bee491096ef49279ba8b8e1f0fca5e37d5faecd"]

# The quorum of the covenants required to sign the transaction
covenant_quorum = 3

# The magic bytes of the network
magic_bytes = "62627434"

# The number of confirmations required for the staking transaction to be mature
w = 100

# Timelock in unbonding transaction
unbonding_time = 1000

# Required fee for unbonding transaction
unbonding_fee = 10000

[server-config]
# The address to listen on
host = "0.0.0.0"

# The port to listen on
port = 9791

# Read timeout in seconds
read-timeout = 15

# Write timeout in seconds
write-timeout = 15

# Idle timeout in seconds
idle-timeout = 120
